### ISSUE TITLE
File Location?

### ISSUE THREAD

**Issue by justinglock40** [desimaniac/docs#1]
Where would I find the file to change for nomodeset on 18.04 that hetzner.cfg does not exist? the first file did and I edited it. Just can't find the grub.d file to edit

**Comment by desimaniac** [comment]
You might not need it. Do you see the contents of `/dev/dri` ?

**Comment by justinglock40** [comment]
I figured it out, That “nomodeset” was in /etc/default/grub

**Comment by desimaniac** [comment]
So the location is `/etc/default/grub/hetzner.cfg` ?

**Comment by justinglock40** [comment]
Nope just /etc/default/grub
  

  
  

  
  
>

**Comment by desimaniac** [comment]
Thanks. Ill add a note in to check there.
