### ISSUE TITLE
HW Transcoding stops working after a while

### ISSUE THREAD

**Issue by kamos69** [desimaniac/docs#3]
Hey. I'm hoping you can help me. I've been running this setup for a while but twice now HW transcoding just stopped working. It would load up the video but then as soon as it needs start transcoding it just hangs forever. No time out, no errors in the Plex logs, it just hangs. Direct streams still work. The weird / bizarre thing is that it works for Roku, iOS and Android clients but stops working for anyone using a browser or windows plex client. The only way to resovle the issue is to either disable HW transcoding or reboot the server. 

I'm running a Hetzner EX61-NVMe. I double checked my config because I thought I might have missed a step but everything looks good. What do you think the issue could be?

**Comment by desimaniac** [comment]
Check your logs. Maybe it’s an issue with your transcode folder and/or permissions.
